config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/about"=>"pages#about"
  get "/contact"=>"pages#contact"

  resources :employees
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :first_name, :last_name, presence: true
    validates :personal_email, presence: true, uniqueness: true

    validates :city, :state, :country, :pincode, :address_line_1, presence: true

    def name
     "#{first_name} #{middle_name} #{last_name}".strip
    end
    def address
      "#{address_line_1} ,#{address_line_2} ,#{city} ,#{state} ,#{country} -#{pincode}  "
    end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
def index
  @employees=Employee.all
end
def new
  @employees =Employee.new
end
def create
  @employees = Employee.new(employee_params)
  if @employees.save
    redirect_to @employees, notice: "Employee was successfully created."
  else
    render :new, status: :unprocessable_entity
  end
end
def destroy
  @employee = Employee.find(params[:id])
  @employee.destroy
  redirect_to employees_path, notice: "Employee was successfully deleted."
end
def edit
  @employees=Employee.find(params[:id])
end
def update
  @employees=Employee.find(params[:id])
  if @employees.update(employee_params)
    redirect_to employees_path, notice: "Employee was successfully updated."
  else
    render :edit
  end
end
def show
  @employee = Employee.find(params[:id])
end

private

def employee_params
  params.require(:employee).permit(:first_name, :middle_name, :last_name, :personal_email, :city, :state, :country, :pincode, :address_line_1, :address_line_2)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @home="welcome nitin"
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users1=User.all
  end
  def new
    @users= User.new
  end
  def create
    @users=User.new(user_param)
    if @users.save
      redirect_to users_path, notice: "Users created successfully."

    else
        render :new, status: :unprocessable_entity
    end
  end
  private
  def user_param
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employees/_eform.html.erb
<%=form_with model:employees do |form|%>
<div class="row">
    <div class="col-lg-4">
        <div class="form-group">
            <%= form.label:first_name,class:"mb-2"%>
            <%= form.text_field:first_name ,class:"form-control form-control-lg"%>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="form-group">
            <%= form.label:middle_name,class:"mb-2"%>
            <%= form.text_field:middle_name ,class:"form-control form-control-lg"%>
        </div>
    </div>
      <div class="col-lg-4">
        <div class="form-group">
            <%= form.label:last_name,class:"mb-2"%>
            <%= form.text_field:last_name ,class:"form-control form-control-lg"%>
        </div>
    </div>
</div>
<div class="row">
      <div class="col-lg-6">
        <div class="form-group">
            <%= form.label:personal_email,class:"mb-2"%>
            <%= form.email_field:personal_email ,class:"form-control form-control-lg"%>
        </div>
       
      </div>
     
        <div class="col-lg-6">
        <div class="form-group">
            <%= form.label:address_line_1,class:"mb-2"%>
            <%= form.text_field:address_line_1 ,class:"form-control form-control-lg"%>
        </div>
      </div>

        <div class="col-lg-3">
        <div class="form-group">
             <%= form.label:city,class:"mb-2" %>
            <%= form.text_field:city ,class:"form-control form-control-lg"%>
        </div>
      </div>

        <div class="col-lg-3">
        <div class="form-group">
            <%= form.label:state,class:"mb-2"%>
            <%= form.text_field:state ,class:"form-control form-control-lg"%>
        </div>
      </div>
        <div class="col-lg-3">
        <div class="form-group">
            <%= form.label:country,class:"mb-2"%>
            <%= form.text_field:country ,class:"form-control form-control-lg"%>
        </div>
      </div>
         <div class="col-lg-3">
        <div class="form-group">
            <%= form.label:pincode,class:"mb-2"%>
            <%= form.text_field:pincode ,class:"form-control form-control-lg"%>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-lg-4">
        <%= form.submit  class:'btn  btn-success btn-lg'%>
      
        <%= link_to 'Back To List' ,"/employees" , class:'btn btn-outline-primary btn-lg'%>
        </div>
      </div>
</div>
<%end%>

app/views/employees/edit.html.erb
<div class="col-lg-12">
    <div class="card mt-5 mb-5">
    <div class="card-body">
        <h2 class="text-center">Update Employyes</h2>
    </div>
</div>
<%= render "employees/eform" , employees:@employees %>
</div>

app/views/employees/index.html.erb
<div class="card mt-5 mb-5">
    <div class="card-body">
        <h2 class="text-center">List of Employyes</h2>
    </div>
</div>
<div class="pt-1 pb-5">
    <%= link_to "New Employee" ,"employees/new" ,class:"btn btn-success btn-lg"%>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th> Name</th>

            <th>email</th>
            <th>address</th>
            <th>Action</th>

        </tr>
    </thead>
    <% @employees.each do |employee|%>

        <tbody>
            <tr>
                <th>
                    <%=employee.name%>
                </th>

                <th>
                    <%=employee.personal_email%>
                </th>
                <th>
                    <%=employee.address%>
                </th>
                <th>
                    <!-- Example single danger button -->
                    <div class="btn-group text-capitalize">
                        <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Action
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to 'Delete' , employee_path(employee.id), method: :delete, data: {
                                    confirm: 'Are you sure?' }, class: "dropdown-item" %>
                            </li>
                            <li>
                                <%= link_to 'show' , employee_path(employee.id), method: :get,
                                    class: "dropdown-item" %>
                            </li>
                            <li>
                                <%= link_to 'update' , edit_employee_path(employee.id), method: :get,
                                    class: "dropdown-item" %>
                            </li>
                        </ul>
                    </div>


                </th>


            </tr>
        </tbody>

        <%end%>
</table>

app/views/employees/new.html.erb
<div class="col-lg-12">
    <div class="card mt-5 mb-5">
    <div class="card-body">
        <h2 class="text-center">New Employyes</h2>
    </div>
</div>
<%= render "employees/eform" , employees:@employees %>
</div>

app/views/employees/show.html.erb
<div class="container text-center ">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-4 ">
      <div class="card p-5" style="width:400px; height:auto;background-color:#dadada;">
        <div class="card-body">
          <h5 class="card-title">
            <%=@employee.name%>
          </h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">
            <%=@employee.personal_email%>
          </h6>
          <p class="card-text">
            <%=@employee.address%>
          </p>
          <%=link_to "Back" ,"/employees", class:"card-link btn btn-primary" %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/includes/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        
        <%= link_to "Home","/",class:"nav-link active" %>
        </li>
        <li class="nav-item">
        
        <%= link_to "About","/about",class:"nav-link active" %>
        </li>
        <li class="nav-item">
        
        <%= link_to "Contact","/contact",class:"nav-link active" %>
        </li>
         <li class="nav-item">
        
        <%= link_to "Employees","/employees",class:"nav-link active" %>
        </li>
        <li class="nav-item">
        
          <%= link_to "Users","/users",class:"nav-link active" %>
          </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "First" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "includes/nav" %>
    <div class="container ">
       <%= yield %>
    </div>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home <%= @home%></h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/index.html.erb
<%= link_to "create","/users/new" %>
<% @users1.each do |user|%>
<p>name<%=user.email%></p>
<%end%>

app/views/users/new.html.erb
<p>new form users</p>

<%=form_with model:@users do |form|%>
<div class="container ">
    <div class="row align-items-center">
        <div class="col-lg-4">
            <%=form.text_field:email ,class:"form-control" %>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-lg-4">
            <%=form.text_field:password ,class:"form-control" %>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-lg-4">
            <%=form.submit class:"btn btn-success" %>
        </div>
    </div>
</div>

<%end%>